# Generated by Django 4.2.11 on 2025-11-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0002_rename_name_student_forename_student_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
